title: Camila Díaz Hermosilla # your name (or website title) here
logo: "images/yo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a class="button button-linked" href="#/" onclick="window.fathom.trackGoal('RHORG9LC', 0);" rel="noopener" role="button"><img class="icon" alt="" src="https://littlelink.io/images/icons/linkedin.svg">LinkedIn</a>
  <br><br>
  
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

.button.button-linked {
  color: #ffffff;
  background-color: #2867b2;
}
.button.button-linked:hover,
.button.button-linked:focus {
  filter: brightness(90%);
}

.button.button-linked {
    color: #ffffff;
    background-color: #2867b2;
}
.button, button {
    display: inline-block;
    text-decoration: none;
    height: 100%;
    text-align: center;
    vertical-align: middle;
    font-size: 18px;
    width: 300px;
    font-weight: 700;
    line-height: 20px;
    padding: 14px 12px 12px 12px;
    letter-spacing: 0.1px;
    white-space: wrap;
    outline: none;
    border-radius: 8px;
    cursor: pointer;
}
