title: Camila Díaz Hermosilla # your name (or website title) here
logo: "images/IMG_7573.HEIC?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hola👋, soy estudiante de medicina de cuarto año con una 
  inclinación hacia la cirugía general, actualmente cursando 
  mis estudios en la <a href="https://www.ufro.cl">UFRO</a>. 
  Además, formo parte de la directiva de diversas organizaciones 
  estudiantiles relacionadas con el ámbito médico.
  <br><br>
  Mi pasión radica en la medicina y en el impacto social que esta 
  puede generar. Mi trabajo es interdisciplinario, abarcando desde 
  la investigación médica hasta la participación en políticas de salud 
  pública y campañas de concienciación. Además de mi interés en la medicina, 
  también tengo un gran interés por las ciencias de la computanción, sobre todo 
  en desarrollo e inteligencia artificial, lo que me permite combinar mis 
  habilidades técnicas con mi vocación médica para crear soluciones 
  innovadoras en el campo de la educación médica.
  <br><br>
  He enfocado mi carrera hacia la cirugía general, y como parte de 
  este enfoque, estoy colaborando en <a href="https://acutem.cl">ACUTEM</a> 
  en mi universidad.

  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
