title: Camila Díaz Hermosilla # your name (or website title) here
logo: "images/yo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">Hola 👋, puedes contactarme en cualquiera de los medios de aquí abajo.</p>
  <!DOCTYPE html>
  <html>
  <head>
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
      .social-icons {
        display: flex;
        justify-content: space-around;
        width: 300px;
        margin: auto;
      }
      .social-icons a {
        color: #267CB9;
        font-size: 24px;
        text-align: center;
        width: 50px;
        height: 50px;
        display: flex;
        align-items: center;
        justify-content: center;
      }
    </style>
  </head>
  <body>
  
    <div class="social-icons">
      <!-- Email -->
      <a href="mailto:c.diaz@ufromail.cl" target="_blank"><i class="fas fa-envelope"></i></a>
      <!-- GitHub -->
      <a href="https://github.com/camiladiazh/" target="_blank"><i class="fab fa-github"></i></a>
      <!-- Instagram -->
      <a href="https://www.instagram.com/camila_diazh/" target="_blank"><i class="fab fa-instagram"></i></a>
      <!-- LinkedIn -->
      <a href="https://www.linkedin.com/in/camila-diaz-hermosilla/" target="_blank"><i class="fab fa-linkedin"></i></a>

    </div>
  

  </body>
  </html>
  <br></br>
  <p align="justify">ℹ️ Si quieres una reunión conmigo para discutir algún proyecto, puedes agendarla en <a href="https://outlook.office.com/bookwithme/user/7de62228a995496abb8cd45f050172e9%40ufromail.cl/meetingtype/7ccda299-bcbc-4d69-ae7e-aa79def661aa?anonymous">este link</a>.</p>


  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

