title: Camila Díaz Hermosilla # your name (or website title) here
logo: "images/yo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify">Hi 👋, thanks for visiting my site. You can reach me through any of the links below.</p>
  <!DOCTYPE html>
  <html>
  <head>
      <!-- Font Awesome CDN -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <style>
        .social-icons {
          display: grid;
          grid-auto-flow: column;
          justify-content: center;
          gap: 20px;
          margin: auto;
        }
        .social-icons a {
          color: #267CB9;
          font-size: 24px;
          text-align: center;
          width: 50px;
          height: 50px;
          display: flex;
          align-items: center;
          justify-content: center;
        }
      </style>
    </head>
  <body>
  
    <div class="social-icons">
      <!-- Email -->
      <a href="mailto:c.diaz@ufromail.cl" target="_blank"><i class="fas fa-envelope"></i></a>
      <!-- GitHub -->
      <a href="https://github.com/camiladiazh/" target="_blank"><i class="fab fa-github"></i></a>
      <!-- Instagram -->
      <a href="https://www.instagram.com/camila_diazh/" target="_blank"><i class="fab fa-instagram"></i></a>
      <!-- LinkedIn -->
      <a href="https://www.linkedin.com/in/camila-diaz-hermosilla/" target="_blank"><i class="fab fa-linkedin"></i></a>

    </div>
  
  </body>
  </html>
  <br></br>
  <p align="justify">ℹ️ If you’d like to schedule a meeting with me to discuss a project or collaboration, you can book a time directly through <a href="https://calendar.notion.so/meet/camiladiazh/agenda">this link</a>.</p>


  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

